name: 'Generic Version Bumpr'
description: 'Github Action that allows you to bump SemVer version for Generic repositories'
inputs:
  version_bump_type:  # id of input
    description: 'Bump Version Type (major, minor, patch)'
    required: true
    default: 'patch'
  version_metadata_path:
    description: 'Path to file containing Version string'
    required: true
    default: 'VERSION'
  generic_version_template:
    description: 'Template used for updating metadata file'
    required: true
    default: 'version := "%d.%d.%d"'
  generic_merge_version_file:
    description: "Don't overwrite the entire version file, but merge using the template pattern"
    type: boolean
    required: false
    default: false
outputs:
  version: # id of output
    description: 'Version that was written to files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PACKAGR_VERSION_BUMP_TYPE: ${{ inputs.version_bump_type }}
    PACKAGR_VERSION_METADATA_PATH: ${{ inputs.version_metadata_path }}
    PACKAGR_GENERIC_VERSION_TEMPLATE: ${{ inputs.generic_version_template }}
    PACKAGR_GENERIC_MERGE_VERSION_FILE: ${{ inputs.generic_merge_version_file }}
branding:
  icon: 'chevrons-up'
  color: 'green'
